version: '3.8'

networks:
  ft_transcendence_network:
    name: ft_transcendence_network
    driver: bridge

volumes:
  database:
   name: database
   driver: local
   driver_opts:
     device: ./database
     type: none
     o: bind


services:

  postgres:
    image: postgres:14
    container_name: postgres_c
    user: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGUSER=postgres
      - POSTGRES_DB=djangoDb
    volumes:
      - ./database:/var/lib/postgresql/data/
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 30s
      timeout: 60s
      retries: 3
      start_period: 80s
    networks:
     - ft_transcendence_network

  backend:
    image: backend:42
    container_name: backend_c
    build:
      context: ./backend
    ports:
      - 8080:8080
    entrypoint: ./entrypoint.sh
    command: bash -c "python manage.py runserver 0.0.0.0:8080"
    environment:
        - DB_HOST=postgres
        - POSTGRES_DB=djangoDb
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    depends_on:
       postgres:
         condition: service_healthy
    restart: always
    networks:
     - ft_transcendence_network

  nginx:
    image: nginx:latest
    container_name: nginx_c
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - 80:80
    depends_on:
      - backend
    restart: always
    networks:
      - ft_transcendence_network
    # remember to expose port 443 for host

