# constants.py
import math

PLAYER_MOVEMENT_UNIT = 9
PLAYGROUND_WIDTH = 220
PLAYGROUND_HEIGHT = 100
MESSAGE_INTERVAL_SECONDS = 0.025
HALF_PLAYER_WIDTH = 1
HALF_PLAYER_HEIGHT = 10
HALF_BALL_SIZE = 1
WALL_MARGIN = 12
BALL_SPEED = 1.5
MAX_BOUNCE_ANGLE_RAD = 30 * math.pi / 180 # Bounce angle in degrees
PLAYER_RIGHT_UP = 'o'
PLAYER_RIGHT_DOWN = 'l'
PLAYER_AI_UP = 'up'
PLAYER_AI_DOWN = 'down'
PLAYER_AI_STAY = 'stay'
PLAYER_LEFT_UP = 'w'
PLAYER_LEFT_DOWN = 's'
START_PAUSE_GAME = 'Enter'
WINNING_SCORE = 5
COLLISION_TOLERANCE = 1e-1
SLOW_DOWN_FACTOR = 3 / 4
SPEED_UP_FACTOR = 1.05
AI_PADDLE_TOLERANCE = 5
