# constants.py
PLAYER_MOVEMENT_UNIT = 1
PLAYGROUND_WIDTH = 180
PLAYGROUND_HEIGHT = 100
MESSAGE_INTERVAL_SECONDS = 0.05  # 50 milliseconds
PLAYER_WIDTH = 4
PLAYER_HEIGHT = 20
BALL_SIZE = 1
WALL_MARGIN = 2
BALL_SPEED = 5
MAX_BOUNCE_ANGLE = 90  # Bounce angle in degrees
MIN_BOUNCE_ANGLE = -90
