# Generated by Django 5.0.4 on 2024-05-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is_staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is_superuser')),
                ('insertTS', models.DateTimeField(auto_now_add=True, null=True, verbose_name='insertTS')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last_login')),
                ('is_online', models.BooleanField(default=False, verbose_name='is_online')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
